# Generated by Django 3.2 on 2022-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('news_header', models.CharField(blank=True, max_length=500, null=True)),
                ('news_data', models.TextField(blank=True, null=True)),
                ('news_type', models.CharField(blank=True, max_length=50, null=True)),
                ('news_images_urls', models.CharField(blank=True, max_length=500, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('record_start_date', models.DateField(blank=True, null=True)),
                ('record_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('news_type', models.CharField(blank=True, max_length=50, null=True)),
                ('new_type_display', models.CharField(blank=True, max_length=100, null=True)),
                ('record_start_date', models.DateField(blank=True, null=True)),
                ('record_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_type',
                'managed': False,
            },
        ),
    ]
